//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruta.GalleryTemplates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ruta.GalleryTemplates.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ajax_loader_dark_gif {
            get {
                object obj = ResourceManager.GetObject("ajax_loader_dark_gif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] empty_gif {
            get {
                object obj = ResourceManager.GetObject("empty_gif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fs_img_g_bg_png {
            get {
                object obj = ResourceManager.GetObject("fs_img_g_bg_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;Image Gallery&lt;/title&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///&lt;!--
        ///@import url(http://fonts.googleapis.com/css?family=Josefin+Sans+Std+Light);
        ///html,body{height:100%;}
        ///*{outline:none;}
        ///body{margin:0px; padding:0px; background:#000;}
        ///#toolbar{position:fixed; z-index:3; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gallery_template {
            get {
                return ResourceManager.GetString("gallery_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] generic_thumbnail_jpg {
            get {
                object obj = ResourceManager.GetObject("generic_thumbnail_jpg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery Easing v1.3 - http://gsgd.co.uk/sandbox/jquery/easing/
        /// *
        /// * Uses the built in easing capabilities added In jQuery 1.1
        /// * to offer multiple easing options
        /// *
        /// * TERMS OF USE - jQuery Easing
        /// * 
        /// * Open source under the BSD License. 
        /// * 
        /// * Copyright © 2008 George McGinley Smith
        /// * All rights reserved.
        /// * 
        /// * Redistribution and use in source and binary forms, with or without modification, 
        /// * are permitted provided that the following conditions are met:
        /// * 
        /// * Redistributions of source code must [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_easing_1_3 {
            get {
                return ResourceManager.GetString("jquery_easing_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] nextImgBtn_png {
            get {
                object obj = ResourceManager.GetObject("nextImgBtn_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pauseImgBtn_png {
            get {
                object obj = ResourceManager.GetObject("pauseImgBtn_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] play2ImgBtn_png {
            get {
                object obj = ResourceManager.GetObject("play2ImgBtn_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] playImgBtn_png {
            get {
                object obj = ResourceManager.GetObject("playImgBtn_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] prevImgBtn_png {
            get {
                object obj = ResourceManager.GetObject("prevImgBtn_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] toolbar_fs_icon_png {
            get {
                object obj = ResourceManager.GetObject("toolbar_fs_icon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] toolbar_n_icon_png {
            get {
                object obj = ResourceManager.GetObject("toolbar_n_icon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
